[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing config
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Remappings for imported libraries
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]